service: crew-backup
configValidationMode: off

provider:
  name: scaleway
  runtime: node18
  stage: production
  scwToken: ${env:API_KEY}
  scwProject: ${env:PROJECT_ID}

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'
    - '!readme.md'
    - '!.npmrc'
    - '!.infisical.json'

functions:
  backup-instance-crew:
    handler: handler.handle
    events:
      - schedule:
          rate: ${env:SCHEDULE_RATE}
    env:
      PROJECT_ID: ${env:PROJECT_ID}
      ZONE: ${env:ZONE}
      VOLUME_ID: ${env:VOLUME_ID}
    secret:
      API_KEY: ${env:API_KEY}
