service: crew-backup
configValidationMode: off
useDotenv: true

provider:
  name: scaleway
  runtime: node14
  stage: production
  scwToken: ${env:API_KEY}
  scwProject: ${env:PROJECT_ID}

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!.gitignore'
    - '!.git/**'

functions:
  backup:
    handler: handler.handle
    events:
      - schedule:
          rate: '${env:SCHEDULE_RATE}'
    env:
      PROJECT_ID: ${env:PROJECT_ID}
      ZONE: ${env:ZONE}
      VOLUME_ID: ${env:VOLUME_ID}
    secret:
      API_KEY: ${env:API_KEY}

